services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: testing
      TZ: 'America/New_York'
    volumes:
      - ./container/oracle/initdb.d:/container-entrypoint-initdb.d

  dev:
    hostname: dev
    container_name: dev
    build:
      dockerfile: Dockerfile
